#!/bin/bash
seed_file='iplist.txt'
host_file='openwrt/hosts.txt'
dnsm_file='openwrt/dnsmasq.conf.txt'
hiwifi_file='hiwifi/hiwifi.txt'

# generate hosts file
single_list=`cat $seed_file | grep -v '^#' | grep -v ^$ | grep -v '^\.'`
echo '127.0.0.1 localhost' > $host_file
for domain in $single_list; do
    echo "127.0.0.1 $domain" >> $host_file
done
# generate dnsmasq.conf file
all_list=`cat $seed_file | grep -v '^#' | grep -v ^$ | grep '^\.'`
echo '# block list' > $dnsm_file
for domain in $all_list;do
    echo "address=/$domain/127.0.0.1" >> $dnsm_file
done

# generate hiwifi block list
cat $seed_file | grep -v '^#' | grep -v ^$ > $hiwifi_file
