#!/bin/bash
# chkconfig: 35 80 10 
# description: Oracle auto start-stop script. 
# 
# Set ORA_HOME to be equivalent to the $ORACLE_HOME 
# from which you wish to execute dbstart and dbshut; 
# 
# Set ORA_OWNER to the user id of the owner of the 
# Oracle database in ORA_HOME. 
ORA_HOME=/home/oracle/oracle_base/product/11.2.0/dbhome_1
ORA_OWNER=oracle

if [ ! -f $ORA_HOME/bin/dbstart ]
then
    echo "Oracle startup: cannot start"
    exit
fi

case "$1" in
    'start')
        # Start the Oracle databases:
        echo "Starting Oracle Databases ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Starting Oracle Databases as part of system up." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/dbstart $ORA_HOME" >>/var/log/oracle.log
        echo "Done"
        # Start the Listener:
        echo "Starting Oracle Listeners ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Starting Oracle Listeners as part of system up." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/lsnrctl start" >>/var/log/oracle.log
        echo "Done."
        # Start the EM:
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Finished." >> /var/log/oracle.log
        echo "Starting Oracle EM ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/emctl start dbconsole" >>/var/log/oracle.log
        echo "Done."
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Finished." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        touch /var/lock/subsys/oracle
        ;;

        'stop')
        # Stop the Oracle EM:
        echo "Stoping Oracle EM ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Stoping Oracle EM as part of system down." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/emctl stop dbconsole" >> /var/log/oracle.log
        echo "Done."
        # Stop the Oracle Listener:
        echo "Stoping Oracle Listeners ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Stoping Oracle Listener as part of system down." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/lsnrctl stop" >> /var/log/oracle.log
        echo "Done."
        rm -f /var/lock/subsys/oracle
        # Stop the Oracle Database:
        echo "Stoping Oracle Databases ... "
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Stoping Oracle Databases as part of system down." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        su - $ORA_OWNER -c "$ORA_HOME/bin/dbshut $ORA_HOME" >>/var/log/oracle.log
        echo "Done."
        echo ""
        echo "-------------------------------------------------" >> /var/log/oracle.log
        date +" %T %a %D : Finished." >> /var/log/oracle.log
        echo "-------------------------------------------------" >> /var/log/oracle.log
        ;;

        'restart')
        $0 stop
        $0 start
        ;;
esac
