#!/bin/bash

# get themes and icons tarball
wget http://cdn.uniteyun.com/gentoo-mint-x.tar.gz

if [ $? -ne 0 ]; then
    echo 'get themes and icons faild'
    exit
fi

# delete old themes
sudo rm -rf /usr/share/themes/Mint-X
sudo rm -rf "/usr/share/themes/Linux Mint"

# delete old icons
sudo rm -rf /usr/share/icons/Mint-X

# install latest themes and icons
tar zxvf gentoo-mint-x.tar.gz -C /
sudo gtk-update-icon-cache /usr/share/icons/Mint-X

# copy gentoo logo
sudo cp -f Gentoo_Linux_logo_matte.svg /usr/share/cinnamon/theme
